### PR TITLE
Update info.rs

### PR DESCRIPTION
**Pull request by DistortedPumpkin**
Give credit to creator :)

### CODE REVIEW

**Review by Drxckzyz — COMMENTED** [review]
Imagine Commenting out The Real Owner, you can be a contributer ;-;

**Review by Drxckzyz — CHANGES_REQUESTED** [review]
Remove the ~~ by the real owners and there will be a contributers section added to the cmd

**Comment by DistortedPumpkin** [comment]
image

**Comment by Drxckzyz** [comment]
lmao

**Review by Drxckzyz — APPROVED** [review]
Looks good, will add as a contributer later

**Comment by DistortedPumpkin** [comment]
changed 
image

**Pull request merged**
